package stringPlagarism.uI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.ScrollPane;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Prathiba R Murthy
 */
public class stringPlagarismOutputUI extends javax.swing.JFrame {

    /**
     * Creates new form StringPlagarismProjectUI
     */
    public stringPlagarismOutputUI() throws FileNotFoundException, IOException {
        initComponents();
        this.setTitle("Plagarism Result ");
        String[] strFiles= new String[5];
        strFiles[0]="/lcss.txt";
        strFiles[1]="/naive.txt";
        strFiles[2]="/kmp.txt";
        strFiles[3]="/boyreMoore.txt";
        strFiles[4]="/rk.txt";
            BufferedReader lcssReader = new BufferedReader(new FileReader("lcss.txt"));
            String line = null;
            while ((line = lcssReader.readLine()) != null) 
            {
             jTextAreaLcss.append(line + "\n");
            }
            BufferedReader kmpReader = new BufferedReader(new FileReader("kmp.txt"));
            line = null;
            while ((line = kmpReader.readLine()) != null) 
            {
            	jTextAreaKmp.append(line + "\n");
            }
            BufferedReader naiveReader = new BufferedReader(new FileReader("naive.txt"));
            line = null;
            while ((line = naiveReader.readLine()) != null) 
            {
            	jTextAreaNaive.append(line + "\n");
            }
            BufferedReader boyerMooreReader = new BufferedReader(new FileReader("boyreMoore.txt"));
            line = null;
            while ((line = boyerMooreReader.readLine()) != null) 
            {
            	jTextAreaBoyerMoore.append(line + "\n");
            }
            BufferedReader rkReader = new BufferedReader(new FileReader("rk.txt"));
            line = null;
            while ((line = rkReader.readLine()) != null) 
            {
            	jTextAreaRabinKarp.append(line + "\n");
            }
            
            lcssReader.close();
            kmpReader.close();
            naiveReader.close();
            boyerMooreReader.close();
            rkReader.close();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLcss = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNaive = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaKmp = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaBoyerMoore = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaRabinKarp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jTextAreaLcss.setEditable(false);
        jTextAreaNaive.setEditable(false);
        jTextAreaKmp.setEditable(false);        jTextAreaBoyerMoore.setEditable(false);
        jTextAreaRabinKarp.setEditable(false);

        jTextAreaLcss.setColumns(20);
        jTextAreaLcss.setLineWrap(true);
        jTextAreaLcss.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLcss);

        jTabbedPane2.addTab("LCSS", jScrollPane1);

        jTextAreaNaive.setColumns(20);
        jTextAreaNaive.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNaive);

        jTabbedPane2.addTab("Naive String Search", jScrollPane2);

        jTextAreaKmp.setColumns(20);
        jTextAreaKmp.setRows(5);
        jScrollPane3.setViewportView(jTextAreaKmp);

        jTabbedPane2.addTab("KMP", jScrollPane3);

        jTextAreaBoyerMoore.setColumns(20);
        jTextAreaBoyerMoore.setRows(5);
        jScrollPane4.setViewportView(jTextAreaBoyerMoore);

        jTabbedPane2.addTab("Boyer-Moore", jScrollPane4);

        jTextAreaRabinKarp.setColumns(20);
        jTextAreaRabinKarp.setRows(5);
        jScrollPane5.setViewportView(jTextAreaRabinKarp);

        jTabbedPane2.addTab("Rabin-Karp", jScrollPane5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stringPlagarismOutputUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stringPlagarismOutputUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stringPlagarismOutputUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stringPlagarismOutputUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new stringPlagarismOutputUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(stringPlagarismOutputUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextAreaLcss;
    private javax.swing.JTextArea jTextAreaNaive;
    private javax.swing.JTextArea jTextAreaKmp;
    private javax.swing.JTextArea jTextAreaBoyerMoore;
    private javax.swing.JTextArea jTextAreaRabinKarp;
    // End of variables declaration                   
}
